In [2]:
import numpy as np

### 1.数组创建函数

In [3]:
# 单位矩阵
a = np.eye(3)
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
a1 = np.array([1,2,3]) # 普通数组
a1

array([1, 2, 3])

In [5]:
a2 = np.arange(1,10,2) # 范围内数组
a2

array([1, 3, 5, 7, 9])

In [6]:
# 全0 全1 数组
a3 = np.zeros((2, 2))
a4 = np.ones((3,3))
a4

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# 创建随机未初始化浮点型数组
a5 = np.empty((2,3))
a5

array([[1.e-323, 0.e+000, 0.e+000],
       [0.e+000, 0.e+000, 0.e+000]])

In [8]:
# 创建线性间隔数组
a6 = np.linspace(1,10, num = 50)
a6

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [9]:
# 创建对数间隔数组 10的几次方
a7 = np.logspace(1,10, num = 10 )
a7[1]

np.float64(100.0)

### 2. 数组操作函数

#### 改变数组形状

In [10]:
m = np.arange(9).reshape(3,3)
m

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 数组拼接 

In [11]:
#  concatenate
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6]])

# 沿行方向拼接（默认 axis=0）(3,2)
result = np.concatenate((a, b))  # 输出：[[1 2], [3 4], [5 6]]
print(result)
# 沿列方向拼接（axis=1） (2,3)
c = np.array([[7], [8]]) 
result_col = np.concatenate((a, c), axis=1)  # 输出：[[1 2 7], [3 4 8]]
print(result_col)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [12]:
# vstack()  hstack()
c1 = np.vstack((a, b))  # 垂直拼接（等价于 axis=0）
c2 = np.hstack((a, c))  # 水平拼接（等价于 axis=1）
print(c1)
print(c2)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 7]
 [3 4 8]]


In [13]:
# stack() 沿新维度堆叠数组（新增一个轴）。
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c3 = np.stack((a, b), axis=0)
c3

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
# dstack()  沿深度方向（第三维度）堆叠数组。
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

dstack_result = np.dstack((a, b))  # 输出形状：(2, 2, 2)
dstack_result

array([[[1, 5],
        [2, 6]],

       [[3, 7],
        [4, 8]]])

In [15]:
# np.c_ 按列方向拼接
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
c = np.c_[a,b]
c

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

#### 数组分割

In [16]:
a = np.split(np.arange(9).reshape(3,3),3)
print(a[1])
print(a)

[[3 4 5]]
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


In [17]:
a = np.hsplit(np.arange(9).reshape(3,3),3)
print(a[1])
print(a)

[[1]
 [4]
 [7]]
[array([[0],
       [3],
       [6]]), array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]])]


In [18]:
a = np.vsplit(np.arange(9).reshape(3,3),3)
print(a[1])
print(a)

[[3 4 5]]
[array([[0, 1, 2]]), array([[3, 4, 5]]), array([[6, 7, 8]])]


#### 按索引取值，赋值

In [19]:
a = np.arange(10)
c = np.take(a,[0,1])
c

array([0, 1])

In [20]:
np.put(a, [1,2] , [-1,-2])
a

array([ 0, -1, -2,  3,  4,  5,  6,  7,  8,  9])

#### 展平操作

In [21]:
# flatten() 改变原数组
a =  np.arange(6).reshape(2,3)
b = a.flatten()
print(a)
print(b)

[[0 1 2]
 [3 4 5]]
[0 1 2 3 4 5]


In [22]:
#  ravel() 不改变原数组
c = a.ravel()
print(c)
print(a)

[0 1 2 3 4 5]
[[0 1 2]
 [3 4 5]]


### 3. 数学函数

In [23]:
# 数组每个元素加 1
a = np.add(1, np.arange(5))
a

array([1, 2, 3, 4, 5])

In [24]:
# 三角函数
a = np.sin(3.14/2)
b = np.cos(3.14/2)
c = np.tan(3.14/2)

In [25]:
# 指数，对数
a = np.exp(1)  
b = np.log(2.718)  # 底是e = ln()
print(a,b)

2.718281828459045 0.999896315728952


### 聚合函数

In [26]:
# 求均值
a = np.arange(9).reshape(3,3)
print(a)
b = np.mean(a,axis=0)
b

[[0 1 2]
 [3 4 5]
 [6 7 8]]


array([3., 4., 5.])

In [27]:
# 求和
b = np.sum(a,axis=0)
b

array([ 9, 12, 15])

In [28]:
# 计算数组的中位数（排序后位于中间的值），对异常值不敏感。
b = np.median(a,axis=0)
b

array([3., 4., 5.])

In [29]:
# 计算标准差（方差的平方根），与原始数据单位一致，更直观反映离散程度。
b = np.std(a,axis=0)
b

array([2.44948974, 2.44948974, 2.44948974])

In [30]:
# 计算方差（数据与均值差异的平方的平均值），衡量数据波动程度
b = np.var(a,axis=0)
b

array([6., 6., 6.])

In [31]:
# 去重
a = np.unique([1,2,2,3,3,3])
a

array([1, 2, 3])

### 特殊值

In [32]:
print(np.e)
print(np.pi)

2.718281828459045
3.141592653589793


### 4.线性代数函数

In [33]:
# 矩阵点乘
a = np.dot([[1,2],[3,4]], [[1,2],[3,4]])
a

array([[ 7, 10],
       [15, 22]])

In [34]:
a =np.array([[1,2],[3,4]])
b = a @ a
b

array([[ 7, 10],
       [15, 22]])

In [35]:
# 矩阵求逆
c = np.linalg.inv(a)
c

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [36]:
# 求矩阵的特征值和特征矩阵
eigVals, eigVects = np.linalg.eig(np.eye(2))

In [37]:
# 求矩阵的奇异值分解
U, S, Vh = np.linalg.svd(a, full_matrices=True)
U

array([[-0.40455358, -0.9145143 ],
       [-0.9145143 ,  0.40455358]])

#### **一、皮尔森相关系数（Pearson Correlation Coefficient）**

衡量两个变量 $X$ 和 $Y$ 之间的 **线性相关程度**，取值范围为 $[-1, 1]$：
- $1$：完全正相关
- $-1$：完全负相关
- $0$：无线性相关

$$
\rho_{X,Y} = \frac{\text{cov}(X,Y)}{\sigma_X \cdot \sigma_Y}
$$
其中：
- $\text{cov}(X,Y)$ 是 $X$ 和 $Y$ 的协方差
- $\sigma_X$ 和 $\sigma_Y$ 是 $X$ 和 $Y$ 的标准差



#### **二、协方差（Covariance）**

衡量两个变量 $X$ 和 $Y$ 的 **共同变化趋势**：
- 正值：变量同向变化
- 负值：变量反向变化

$$
\text{cov}(X,Y) = \frac{1}{n-1} \sum_{i=1}^n (x_i - \bar{x})(y_i - \bar{y})
$$
- **注意**：分母为 $n-1$ 时是样本协方差（无偏估计），分母为 $n$ 时为总体协方差。



### **四、关键区别**
| 指标                | 意义                           | 范围          | 标准化 |
|---------------------|--------------------------------|---------------|--------|
| **协方差**          | 变量共同变化趋势的强度         | $(-\infty, +\infty)$ | 否     |
| **皮尔森相关系数**  | 标准化后的协方差（无量纲）     | $[-1, 1]$   | 是     |





In [38]:
# 计算协方差矩阵
np.cov(a, rowvar=0)  # rowvar=False 表示每列是一个特征

array([[2., 2.],
       [2., 2.]])

### 5.统计函数

In [39]:
# min ,max
a = np.arange(10)
b = np.min(a)
b

np.int64(0)

In [40]:
# argmin , argmax
b = np.argmax(a)
b

np.int64(9)

In [41]:
# 生成坐标矩阵
a = np.linspace(1 , 10 , num =10)
b = np.linspace(1 , 10 , num =10)
x,y = np.meshgrid(a,b)
m = np.c_[x.ravel(),y.ravel()]
m

array([[ 1.,  1.],
       [ 2.,  1.],
       [ 3.,  1.],
       [ 4.,  1.],
       [ 5.,  1.],
       [ 6.,  1.],
       [ 7.,  1.],
       [ 8.,  1.],
       [ 9.,  1.],
       [10.,  1.],
       [ 1.,  2.],
       [ 2.,  2.],
       [ 3.,  2.],
       [ 4.,  2.],
       [ 5.,  2.],
       [ 6.,  2.],
       [ 7.,  2.],
       [ 8.,  2.],
       [ 9.,  2.],
       [10.,  2.],
       [ 1.,  3.],
       [ 2.,  3.],
       [ 3.,  3.],
       [ 4.,  3.],
       [ 5.,  3.],
       [ 6.,  3.],
       [ 7.,  3.],
       [ 8.,  3.],
       [ 9.,  3.],
       [10.,  3.],
       [ 1.,  4.],
       [ 2.,  4.],
       [ 3.,  4.],
       [ 4.,  4.],
       [ 5.,  4.],
       [ 6.,  4.],
       [ 7.,  4.],
       [ 8.,  4.],
       [ 9.,  4.],
       [10.,  4.],
       [ 1.,  5.],
       [ 2.,  5.],
       [ 3.,  5.],
       [ 4.,  5.],
       [ 5.,  5.],
       [ 6.,  5.],
       [ 7.,  5.],
       [ 8.,  5.],
       [ 9.,  5.],
       [10.,  5.],
       [ 1.,  6.],
       [ 2.,  6.],
       [ 3.,

### 6. 随机数生成

In [ ]:
# 均匀分布 [0,1)
a = np.random.rand(3)
a

array([0.56651564, 0.50041994, 0.9331005 ])

In [ ]:
# 正态分布 （均值为 0，标准差为 1）
a = np.random.randn(3)
a

array([ 0.94764518, -1.42152669,  0.87051846])

In [49]:
# 随机整数
a  = np.random.randint(1,10)
a

8

In [50]:
# 随机采样
a = np.random.choice([1,2,3] , size = 2)
a

array([2, 1])

### 7. 数据类型操作

In [52]:
# 转换数组数据类型
a = np.array([1.7, 2.2 , 3.3]).astype(int)
a

array([1, 2, 3])

In [55]:
# round() 四舍五入
a = np.array([1.7, 2.2 , 3.3])
b = np.round(a)
b

array([2., 2., 3.])

In [ ]:
# ceil() 向上取整
b = np.ceil(a)
b

array([2., 3., 4.])

In [56]:
# floor() 向下取整
b = np.floor(a)
b

array([1., 2., 3.])

### 8. 副本与视图

#### 拷贝

In [ ]:
# 深拷贝， 创建副本，不改变原数组
a = np.array([1.7, 2.2 , 3.3])
b = a.copy()
a[2] = 0
b

array([1.7, 2.2, 3.3])

In [ ]:
#  浅拷贝， 拷贝对象元素的引用，创建的是视图
a = np.array([1.7, 2.2 , 3.3])
c = a[:]
a[2] = 0
c

array([1.7, 2.2, 0. ])

### 9. 洗牌操作

In [ ]:
# `np.random.permutation`: 随机排列数组,返回新数组
arr = np.array([1, 2, 3, 4])
res = np.random.permutation(arr)  # 示例输出 array([3, 1, 4, 2])
print("原数组：" , arr)
print("洗牌结果：",res)

原数组： [1 2 3 4]
洗牌结果： [3 2 1 4]


In [69]:
# `np.random.shuffle` :会原地修改原数组,无返回值
arr = np.array([1, 2, 3, 4])
np.random.shuffle(arr) 
print("原数组：" , arr)

原数组： [4 1 3 2]


In [ ]:
"""清洗数据操作
    因为清洗数据时，需要清洗特征和对应标签两个数组,
    不能使用np.random.shuffle对两组数据同时洗牌,
    这样洗牌会导致样本与标签不对应！
"""
features = np.array([[1,2] ,[6,3] , [7,8], [12,24]])
labels =np.array( [1,2,3,4])
indices = np.random.permutation(len(features))
shuffled_features = features[indices]
shuffled_labels = labels[indices ]
print(shuffled_features)
print(shuffled_labels)


[[1 2]
 [7 8]
 [6 3]]
[1 3 2]


NumPy数组的高级索引（Fancy Indexing）功能。让我们逐步分析：

1. **数组定义**：
   - `a = np.array([3, 2, 1, 0])`：创建一个NumPy数组 `a`，包含索引值 `[3, 2, 1, 0]`。
   - `b = np.array([1, 2, 3, 4])`：创建一个NumPy数组 `b`，元素为 `[1, 2, 3, 4]`。

2. **索引操作**：
   - `c = b[a]`：使用数组 `a` 中的值作为索引，从数组 `b` 中提取对应的元素。
   - 索引规则：
     - `a[0] = 3` → 提取 `b[3]`（值为4）
     - `a[1] = 2` → 提取 `b[2]`（值为3）
     - `a[2] = 1` → 提取 `b[1]`（值为2）
     - `a[3] = 0` → 提取 `b[0]`（值为1）

3. **结果**：
   - `c` 将包含 `[4, 3, 2, 1]`，即按照 `a` 提供的索引顺序重组 `b` 的元素。

**关键点**：
- **高级索引**：允许用一个数组作为索引，提取目标数组的多个元素。
- **索引顺序**：结果数组 `c` 的形状与索引数组 `a` 的形状一致。
- **边界安全**：索引值必须在目标数组的有效范围内（此处 `a` 的值均为 `0-3`，与 `b` 的索引范围匹配）。


In [75]:
a = np.array([3,2,1,0])
b = np.array([1,2,3,4])
c =b[a]
c

array([4, 3, 2, 1])

### 10.排序操作

In [ ]:
# sort() 
a = np.sort([3,1,2])
a

array([1, 2, 3])

In [ ]:
# argsort() 返回排序后的索引
a = np.argsort([3,1,2])
a

array([1, 2, 0])

In [ ]:
# searchgsort() 有序数组中查找元素的索引
a  = np.searchsorted([1,2,3,4,5] , 3)
a

np.int64(2)